# Generated by Django 5.2.4 on 2025-07-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0002_role'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='sos_role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='sos_user',
        ),
    ]
