# Generated by Django 5.2.4 on 2025-07-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0003_alter_role_table_alter_user_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sos_college',
            },
        ),
    ]
