# Generated by Django 5.2.4 on 2025-07-21 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ORS', '0004_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sos_course',
            },
        ),
    ]
